### ISSUE TITLE
User data not available in question obj

### ISSUE THREAD

**Issue by andela-bebowe** [andela-iamadi/zhishi-backend#18]
Question object should contain user object that contains user image and user full_name.

Question object should contain vote_counts, answer_counts, view_counts.

Question object should contain time_updated in readable format e.g two days ago, one hour ago.

**Comment by andela-echigbo** [comment]
We already have the `votes` and `answers` of a question returned as an array of objects, maybe the frontend can take the `size` of these arrays. Or do we have to return them as a separate attributes of the question?

**Comment by andela-bebowe** [comment]
Ok.
For all questions, one will not need their individual answers or votes, all that will be needed is the count.
Why give us all this objects and arrays of objects that could contain other objects, when all we need is the count.

**Comment by andela-bebowe** [comment]
For a single question show page, it is ok to send an array of answers and votes, along with it.
